-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.expenses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    purchased_at date NOT NULL,
    receipts jsonb[],
    user_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.expenses
    OWNER to postgres;

ALTER TABLE IF EXISTS public.expenses
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.expenses TO anon;

GRANT ALL ON TABLE public.expenses TO authenticated;

GRANT ALL ON TABLE public.expenses TO postgres;

GRANT ALL ON TABLE public.expenses TO service_role;
CREATE POLICY "Enable insert for authenticated users only"
    ON public.expenses
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Enable select for users based on user_id"
    ON public.expenses
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.uid() = user_id));
