name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubunty-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: action/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install deps
        run: npm i
      - name: Build storybook
        run: npm run build-storybook -o ./dist/storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages/@v3
        with:
          personal-token: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: ./dist
