name: 🐶 Check for Merge
on:
  pull_request:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: enable node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm install
        run: npm ci
      - name: ESLint
        run: npm run lint
  vrt:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: enable node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: npm install
        run: npm ci
      - name: publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./src
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          projectToken: ${{ secrets.CHROMATIC_SECRET }}
        env:
          SUPABASE_URL: ${{ steps.chromatic.outputs.storybookUrl }},
          SUPABASE_ANON_KEY: dammy_key
