name: 🐶 Check for Merge
on:
  pull_request:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: enable node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm install
        run: npm ci
      - name: ESLint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: enable node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm install
        run: npm ci
      - name: testing and publish coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: { { secrets.CC_TEST_REPORTER_ID } }
        with:
          coverageCommand: npm run test:coverage
          debug: true
  vrt:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: enable node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - name: npm install
        run: npm ci
      - name: publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./src
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          projectToken: ${{ secrets.CHROMATIC_SECRET }}
